version: '3'

services:
  hist130-quiz:
    build:
      context: .
    restart: unless-stopped
    ports:
      - 3130:3130
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
